global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'log_consumer'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['consumer:8000']

  - job_name: 'kafka'
    static_configs:
      - targets: ['kafka-exporter:9308']

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090'] 